apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: davp-demo12
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: davp-demo12 
  name: davp-demo12
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: davp-demo12 
